-- MySQL Script generated by MySQL Workbench
-- 01/31/15 15:42:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema weather_station
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema weather_station
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weather_station` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `weather_station` ;

-- -----------------------------------------------------
-- Table `weather_station`.`records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather_station`.`records` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `humidity` FLOAT NULL DEFAULT 0,
  `pressure` FLOAT NULL DEFAULT 0,
  `temperature` FLOAT NULL DEFAULT 0,
  `illuminance` FLOAT NULL DEFAULT 0,
  `dewpoint` FLOAT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `weather_station`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather_station`.`logs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `message` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
